#   docker-compose up
#   docker exec -it kafka-docker_kafka_1 /bin/bash
#   kafka-topics.sh --bootstrap-server :9092 --list
#   kafka-topics.sh --bootstrap-server :9092 --create --topic t1 --partitions 3 --replication-factor 1
#   docker-compose rm

version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'